/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package codigo;

/**
 *
 * @author Usuario
 */
public class VentanaCalculadora extends javax.swing.JFrame {

    
    double operando1 = 0; // guarda el primer número que montamo.
    String operacion = ""; // guarda la operación pulsada.
    
    
    public VentanaCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        display = new javax.swing.JLabel();
        boton07 = new javax.swing.JButton();
        boton08 = new javax.swing.JButton();
        boton09 = new javax.swing.JButton();
        boton03 = new javax.swing.JButton();
        boton06 = new javax.swing.JButton();
        boton05 = new javax.swing.JButton();
        boton04 = new javax.swing.JButton();
        boton01 = new javax.swing.JButton();
        boton02 = new javax.swing.JButton();
        boton00 = new javax.swing.JButton();
        botondivision = new javax.swing.JButton();
        botonsuma = new javax.swing.JButton();
        botonresta = new javax.swing.JButton();
        botonmulti = new javax.swing.JButton();
        botondivision1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        display.setBackground(new java.awt.Color(0, 0, 0));
        display.setFont(new java.awt.Font("Bookman Old Style", 1, 36)); // NOI18N
        display.setForeground(new java.awt.Color(255, 0, 255));
        display.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        display.setText("0");
        display.setOpaque(true);
        getContentPane().add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 376, 54));

        boton07.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton07.setText("7");
        boton07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton07ActionPerformed(evt);
            }
        });
        getContentPane().add(boton07, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 85, 64, 64));

        boton08.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton08.setText("8");
        boton08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton08ActionPerformed(evt);
            }
        });
        getContentPane().add(boton08, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 85, 64, 64));

        boton09.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton09.setText("9");
        boton09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton09ActionPerformed(evt);
            }
        });
        getContentPane().add(boton09, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 85, 64, 64));

        boton03.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton03.setText("3");
        boton03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton03ActionPerformed(evt);
            }
        });
        getContentPane().add(boton03, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 249, 64, 64));

        boton06.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton06.setText("6");
        boton06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton06ActionPerformed(evt);
            }
        });
        getContentPane().add(boton06, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 167, 64, 64));

        boton05.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton05.setText("5");
        boton05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton05ActionPerformed(evt);
            }
        });
        getContentPane().add(boton05, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 167, 64, 64));

        boton04.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton04.setText("4");
        boton04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton04ActionPerformed(evt);
            }
        });
        getContentPane().add(boton04, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 167, 64, 64));

        boton01.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton01.setText("1");
        boton01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton01ActionPerformed(evt);
            }
        });
        getContentPane().add(boton01, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 249, 64, 64));

        boton02.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton02.setText("2");
        boton02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton02ActionPerformed(evt);
            }
        });
        getContentPane().add(boton02, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 249, 64, 64));

        boton00.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton00.setText("0");
        boton00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton00ActionPerformed(evt);
            }
        });
        getContentPane().add(boton00, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 320, 60, 64));

        botondivision.setText("/");
        botondivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botondivisionActionPerformed(evt);
            }
        });
        getContentPane().add(botondivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 64, 64));

        botonsuma.setText("+");
        botonsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonsumaActionPerformed(evt);
            }
        });
        getContentPane().add(botonsuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 87, 64, 64));

        botonresta.setText("-");
        botonresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonrestaActionPerformed(evt);
            }
        });
        getContentPane().add(botonresta, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 167, 64, 64));

        botonmulti.setText("*");
        botonmulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmultiActionPerformed(evt);
            }
        });
        getContentPane().add(botonmulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 249, 64, 64));

        botondivision1.setText("=");
        botondivision1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botondivision1ActionPerformed(evt);
            }
        });
        getContentPane().add(botondivision1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 150, 64));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton07ActionPerformed
        String auxiliar = display.getText();
        if (auxiliar.equals("0") ){
                    display.setText( "7");
        }else{
                 display.setText(auxiliar + "7");   
        }
    }//GEN-LAST:event_boton07ActionPerformed

    private void boton08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton08ActionPerformed
        String auxiliar = display.getText();
        if (auxiliar.equals("0") ){
                    display.setText( "8");
        }else{
                 display.setText(auxiliar + "8");   
            }
          }//GEN-LAST:event_boton08ActionPerformed

    private void boton09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton09ActionPerformed
                String auxiliar = display.getText();
        if (auxiliar.equals("0") ){
                    display.setText( "9");
        }else{
                 display.setText(auxiliar + "9");   
        }
    }//GEN-LAST:event_boton09ActionPerformed

    private void boton03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton03ActionPerformed
               String auxiliar = display.getText();
        if (auxiliar.equals("0") ){
                    display.setText( "3");
        }else{
                 display.setText(auxiliar + "3");   
        }
    }//GEN-LAST:event_boton03ActionPerformed

    private void boton06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton06ActionPerformed
                String auxiliar = display.getText();
        if (auxiliar.equals("0") ){
                    display.setText( "6");
        }else{
                 display.setText(auxiliar + "6");   
        }
    }//GEN-LAST:event_boton06ActionPerformed

    private void boton05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton05ActionPerformed
               String auxiliar = display.getText();
        if (auxiliar.equals("0") ){
                    display.setText( "5");
        }else{
                 display.setText(auxiliar + "5");   
        }
    }//GEN-LAST:event_boton05ActionPerformed

    private void boton04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton04ActionPerformed
               String auxiliar = display.getText();
        if (auxiliar.equals("0") ){
                    display.setText( "4");
        }else{
                 display.setText(auxiliar + "4");   
        }
    }//GEN-LAST:event_boton04ActionPerformed

    private void boton01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton01ActionPerformed
               String auxiliar = display.getText();
        if (auxiliar.equals("0") ){
                    display.setText( "1");
        }else{
                 display.setText(auxiliar + "1");   
        }
    }//GEN-LAST:event_boton01ActionPerformed

    private void boton02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton02ActionPerformed
               String auxiliar = display.getText();
        if (auxiliar.equals("0") ){
                    display.setText( "2");
        }else{
                 display.setText(auxiliar + "2");   
        }
    }//GEN-LAST:event_boton02ActionPerformed

    private void boton00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton00ActionPerformed
               String auxiliar = display.getText();
        if (auxiliar.equals("0") ){
                    display.setText( "0");
        }else{
                 display.setText(auxiliar + "0");   
        }
    }//GEN-LAST:event_boton00ActionPerformed

    private void botondivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botondivisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botondivisionActionPerformed

    private void botonsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonsumaActionPerformed
        operacion = "+";
        //Double.valueof convierte un string
        //en su equivalente numerico
        operando1 = Double.valueOf(display.getText());
        //reseteo la pantalla
        display.setText("0");
        
    }//GEN-LAST:event_botonsumaActionPerformed

    private void botonrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonrestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonrestaActionPerformed

    private void botonmultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmultiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonmultiActionPerformed

    private void botondivision1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botondivision1ActionPerformed
        double operando2 = Double.valueOf(display.getText());
        if (operacion.equals("+")){
            operando1 = operando1 + operando2;
        }
        
        display.setText("" + operando1);
    }//GEN-LAST:event_botondivision1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton00;
    private javax.swing.JButton boton01;
    private javax.swing.JButton boton02;
    private javax.swing.JButton boton03;
    private javax.swing.JButton boton04;
    private javax.swing.JButton boton05;
    private javax.swing.JButton boton06;
    private javax.swing.JButton boton07;
    private javax.swing.JButton boton08;
    private javax.swing.JButton boton09;
    private javax.swing.JButton botondivision;
    private javax.swing.JButton botondivision1;
    private javax.swing.JButton botonmulti;
    private javax.swing.JButton botonresta;
    private javax.swing.JButton botonsuma;
    private javax.swing.JLabel display;
    // End of variables declaration//GEN-END:variables
}
